project:
  type: website

website:
  title: "biostat840-intro-kinnary-shah"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - data_analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto