project:
  type: website

website:
  title: "biostat840-intro-kinnary-shah"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: data_analysis.qmd
        text: Example Analysis

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto